config/routes.rb
Rails.application.routes.draw do
  resources :books do
    collection do
      get :petition
    end
  end
  root 'users#profile'
  resources :users, only: [] do
    collection do
      get :buyed_books
      post :buy_books
      get :profile
      put '/:book_id/release', to: 'users#release', as: 'release'
      get :availables
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:available, :reserved, :buyed, :requested]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book=Book.new(book_params)
    @book.user=current_user
    if @book.save
      render json: @book, status: :ok
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_petition
    @book=Book.new(book_params)
    @book.save
    render json: {number: @book.id}
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def petition
    @book=Book.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :price, :status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_book, only: :release
  
  def profile
    @books=current_user.books.reserved
  end

  def availables
    @books=Book.available
  end

  def release
    @book.update_attributes(status: params[:status], user: current_user)
    redirect_to profile_users_path
  end

  def buyed_books
    @books=current_user.books.reserved.pluck(:title, :id)
  end

  def buy_book
    @book.update_attributes(status: params[:status], user: current_user)
    redirect_to root_path
  end
  def set_book
    @book=Book.find(params[:book_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<%= link_to 'Solicitar Libro', petition_books_path, class: "btn btn-info m-3" %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.status %></td>
        <td><%= book.user_id %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/petition.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <h3>Solicita un libro</h3>
    <%= form_with model: @book, url: petition_books_path do |f|%>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Nombre Libro"%>
      </div>
      <div class="form-group">
        <%= f.hidden_field :status, value: 'requested'%>
      </div>
      <div class="form-group">
        <%= f.submit 'Solicitar', class: "btn btn-primary form-control request-book"%>
      </div>
    <%end%>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @book.user_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksLender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'  %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path(current_user.id), method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Libros disponibles', availables_users_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/availables.html.erb
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.status %></td>
        <td><%= book.user_id %></td>
        <td><%= link_to 'Reservar', release_users_path(book_id: book.id, status: :reserved), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/buyed_books.html.erb
<h1>Users#buyed_books</h1>
<p>Find me in app/views/users/buyed_books.html.erb</p>

<%= form_with url: buy_books_users_path do |f| %>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.select :book_id, @books, class: "custom-select" %>
    <%= f.hidden_field :status, value: :buyed %>
    <%= f.submit 'Comprar', class: "btn btn-success m-3", data: {confirm: 'Estás segur@?'} %>
  </div>
<% end %>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>
<%= link_to 'Comprar Libro', buyed_books_users_path, class: "btn btn-primary m-3" %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.status %></td>
        <td><%= book.user_id %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Liberar', release_users_path(book_id: book.id, status: :available), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>